### PR TITLE
Allow the version of an artifact to be a variable

### PR DESCRIPTION
**Pull request by Darkade**
The following changes are introduced:
 * If a package is not found in one repo (status 404) try the next repo in config
 * Repos config name changed to `.jip_config`
 * If the version of an Artifact is a variable `${version}` check the properties tag in the pom for the proper version

### CODE REVIEW

**Comment by sunng87** [comment]
Thanks for the patch. But according to our travis CI, this change will break jip on 2.6 platform. I still hope we can support 2.6 if it's possible.

**Comment by Darkade** [comment]
I changed some old % string formatting to .format, it's clearer to me. I just returned to the old formatting.

**Comment by sunng87** [comment]
Thanks for the patch!

**Comment by Darkade** [comment]
Thank you

**Pull request merged**
