### PR TITLE
Follow PEP 440 for development versions

### PR DESCRIPTION
**Pull request by wikier**
https://www.python.org/dev/peps/pep-0440/#developmental-releases

### CODE REVIEW

**Comment by wikier** [comment]
BTW, when is `0.9.8` planned to be released?

**Comment by sunng87** [comment]
Nice, I will release it later today.

BTW, would you like to join the development of this tool? I'm no longer working on jython related things so I have little time to spend on this project. If you are interested in this project, I will create a github organization for it.

**Comment by wikier** [comment]
Thanks, @sunng87.

I could try to help, sure. I'm currently using it embedded API for a project will be released soon, so I may find some time to maintain it and fix issues.

**Comment by sunng87** [comment]
Cool, thanks @wikier !

**Pull request merged**
